package com.bravedroid.rentcar.shared.infrastructure.persistence.entities

import com.bravedroid.rentcar.shared.domain.User
import java.sql.Date

data class UserEntity(
  val id: Long? = null,// autoGenerated
  val idNetwork: Long,
  val name: String,
  val sex: Int,
  val createdAt: Date
) {
  companion object {
    fun User.toUserEntity(_id: Long? = null): UserEntity =
      UserEntity(
        id = _id,
        idNetwork = id,
        name = name,
        sex = sex,
        createdAt = Date(System.currentTimeMillis())
      )
  }
}
