package com.bravedroid.rentcar.shared.infrastructure.persistence.entities

import com.bravedroid.rentcar.shared.domain.User
import java.sql.Date

data class UserEntity(
    val id: Long? = null,// autoGenerated
    //val id: Long = -1L,// autoGenerated
    val name: String,
    val sex: Int,
    val createdAt: Date
) {
    companion object {
        fun User.toUserEntity(): UserEntity =
            UserEntity(
                id = id,
                name = name,
                sex = sex,
                createdAt = Date(System.currentTimeMillis())
            )
    }

    override fun equals(other: Any?): Boolean {
        return other is UserEntity
                && this.id == other.id
                && this.name == other.name
                && this.sex == other.sex
    }
}
